export const SIGN_UP = {
    REQUEST_ALL: 'REQUEST_ALL_USER_SIGN_UP',
    RESPONSE_ALL: 'RESPONSE_ALL_USER_SIGN_UP',
    REQUEST : 'REQUEST_SIGN_UP',
    ERROR: 'ERROR_SIGN_UP',
    SUCCESS: 'SUCCESS_SIGN_UP'
}
export const LOGIN = {
    REQUEST_ADMIN : 'REQUEST_LOGIN_ADMIN',
    ERROR_ADMIN: 'ERROR_LOGIN_ADMIN',
    SUCCESS_ADMIN: 'SUCCESS_LOGIN_ADMIN',
    REQUEST_LOGIN : 'REQUEST_LOGIN',
    ERROR_LOGIN: 'ERROR_LOGIN',
    SUCCESS_LOGIN: 'SUCCESS_LOGIN',
}
export const USER = {
    REQUEST_ALL: 'REQUEST_ALL_USER',
    RESPONSE_ALL: 'RESPONSE_ALL_USER',
    REQUEST_EDIT: 'REQUEST_EDIT_USER',
    RESPONSE_EDIT: 'RESPONSE_EDIT_USER',
    REQUEST_DELETE: 'REQUEST_DELETE_USER',
    RESPONSE_DELETE: 'RESPONSE_DELETE_USER',
    REQUEST_ONE: 'REQUEST_ONE_USER',
    RESPONSE_ONE: 'RESPONSE_ONE_USER',
    SUCCESS: 'SUCCESS_USER',
    ERROR: 'ERROR_USER',
    REQUEST_SEARCH: 'REQUEST_SEARCH_USER',
    RESPONSE_SEARCH: 'RESPONSE_SEARCH_USER'
}
export const CAT = {
    REQUEST_ALL: 'REQUEST_ALL_CAT',
    RESPONSE_ALL: 'RESPONSE_ALL_CAT',
    REQUEST_ADD: 'REQUEST_ADD_CAT',
    RESPONSE_ADD: 'RESPONSE_ADD_CAT',
    REQUEST_EDIT: 'REQUEST_EDIT_CAT',
    RESPONSE_EDIT: 'RESPONSE_EDIT_CAT',
    REQUEST_DELETE: 'REQUEST_DELETE_CAT',
    RESPONSE_DELETE: 'RESPONSE_DELETE_CAT',
    REQUEST_ONE: 'REQUEST_ONE_CAT',
    RESPONSE_ONE: 'RESPONSE_ONE_CAT',
    SUCCESS: 'SUCCESS_CAT',
    ERROR: 'ERROR_CAT',
    REQUEST_SEARCH: 'REQUEST_SEARCH_CAT',
    RESPONSE_SEARCH: 'RESPONSE_SEARCH_CAT'
}
export const PRODUCT = {
    REQUEST_ALL: 'REQUEST_ALL_PRODUCT',
    RESPONSE_ALL: 'RESPONSE_ALL_PRODUCT',
    REQUEST_ADD: 'REQUEST_ADD_PRODUCT',
    RESPONSE_ADD: 'RESPONSE_ADD_PRODUCT',
    REQUEST_EDIT: 'REQUEST_EDIT_PRODUCT',
    RESPONSE_EDIT: 'RESPONSE_EDIT_PRODUCT',
    REQUEST_DELETE: 'REQUEST_DELETE_PRODUCT',
    RESPONSE_DELETE: 'RESPONSE_DELETE_PRODUCT',
    REQUEST_ONE: 'REQUEST_ONE_PRODUCT',
    RESPONSE_ONE: 'RESPONSE_ONE_PRODUCT',
    SUCCESS: 'SUCCESS_PRODUCT',
    ERROR: 'ERROR_PRODUCT',
    REQUEST_SEARCH: 'REQUEST_SEARCH_PRODUCT',
    RESPONSE_SEARCH: 'RESPONSE_SEARCH_PRODUCT'
}